/* ═══════════════════════════════════════════════
   F1 2026 — Data
   ═══════════════════════════════════════════════ */

const DRIVERS = [
  { pos: 1, name: 'A. Antonelli', full: 'Andrea Kimi Antonelli', s: 'ANT', team: 'Mercedes', pts: 156, num: 12, nat: '🇮🇹', wins: 4, poles: 3, born: '2006', from: 'Bologna, Italy' },
  { pos: 2, name: 'L. Hamilton', full: 'Lewis Hamilton', s: 'HAM', team: 'Ferrari', pts: 90, num: 44, nat: '🇬🇧', wins: 1, poles: 2, born: '1985', from: 'Stevenage, UK' },
  { pos: 3, name: 'G. Russell', full: 'George Russell', s: 'RUS', team: 'Mercedes', pts: 88, num: 63, nat: '🇬🇧', wins: 1, poles: 1, born: '1998', from: 'King\'s Lynn, UK' },
  { pos: 4, name: 'C. Leclerc', full: 'Charles Leclerc', s: 'LEC', team: 'Ferrari', pts: 75, num: 16, nat: '🇲🇨', wins: 0, poles: 2, born: '1997', from: 'Monte Carlo' },
  { pos: 5, name: 'O. Piastri', full: 'Oscar Piastri', s: 'PIA', team: 'McLaren', pts: 60, num: 81, nat: '🇦🇺', wins: 0, poles: 0, born: '2001', from: 'Melbourne, AU' },
  { pos: 6, name: 'L. Norris', full: 'Lando Norris', s: 'NOR', team: 'McLaren', pts: 58, num: 4, nat: '🇬🇧', wins: 0, poles: 0, born: '1999', from: 'Bristol, UK' },
  { pos: 7, name: 'M. Verstappen', full: 'Max Verstappen', s: 'VER', team: 'Red Bull', pts: 43, num: 1, nat: '🇳🇱', wins: 0, poles: 0, born: '1997', from: 'Hasselt, Belgium' },
  { pos: 8, name: 'I. Hadjar', full: 'Isack Hadjar', s: 'HAD', team: 'Red Bull', pts: 29, num: 6, nat: '🇫🇷', wins: 0, poles: 0, born: '2004', from: 'Paris, France' },
  { pos: 9, name: 'L. Lawson', full: 'Liam Lawson', s: 'LAW', team: 'Racing Bulls', pts: 26, num: 30, nat: '🇳🇿', wins: 0, poles: 0, born: '2002', from: 'Hastings, NZ' },
  { pos: 10, name: 'P. Gasly', full: 'Pierre Gasly', s: 'GAS', team: 'Alpine', pts: 26, num: 10, nat: '🇫🇷', wins: 0, poles: 0, born: '1996', from: 'Rouen, France' },
  { pos: 11, name: 'O. Bearman', full: 'Oliver Bearman', s: 'BEA', team: 'Haas', pts: 18, num: 87, nat: '🇬🇧', wins: 0, poles: 0, born: '2005', from: 'Chelmsford, UK' },
  { pos: 12, name: 'F. Colapinto', full: 'Franco Colapinto', s: 'COL', team: 'Alpine', pts: 15, num: 43, nat: '🇦🇷', wins: 0, poles: 0, born: '2003', from: 'Buenos Aires' },
  { pos: 13, name: 'A. Lindblad', full: 'Arvid Lindblad', s: 'LIN', team: 'Racing Bulls', pts: 13, num: 7, nat: '🇸🇪', wins: 0, poles: 0, born: '2006', from: 'Stockholm, Sweden' },
  { pos: 14, name: 'C. Sainz', full: 'Carlos Sainz', s: 'SAI', team: 'Williams', pts: 6, num: 55, nat: '🇪🇸', wins: 0, poles: 0, born: '1994', from: 'Madrid, Spain' },
  { pos: 15, name: 'A. Albon', full: 'Alexander Albon', s: 'ALB', team: 'Williams', pts: 5, num: 23, nat: '🇹🇭', wins: 0, poles: 0, born: '1996', from: 'London, UK' },
  { pos: 16, name: 'E. Ocon', full: 'Esteban Ocon', s: 'OCO', team: 'Haas', pts: 3, num: 31, nat: '🇫🇷', wins: 0, poles: 0, born: '1996', from: 'Évreux, France' },
  { pos: 17, name: 'G. Bortoleto', full: 'Gabriel Bortoleto', s: 'BOR', team: 'Audi', pts: 2, num: 5, nat: '🇧🇷', wins: 0, poles: 0, born: '2004', from: 'São Paulo, Brazil' },
  { pos: 18, name: 'F. Alonso', full: 'Fernando Alonso', s: 'ALO', team: 'Aston Martin', pts: 1, num: 14, nat: '🇪🇸', wins: 0, poles: 0, born: '1981', from: 'Oviedo, Spain' },
  { pos: 19, name: 'N. Hülkenberg', full: 'Nico Hülkenberg', s: 'HUL', team: 'Audi', pts: 0, num: 27, nat: '🇩🇪', wins: 0, poles: 0, born: '1987', from: 'Emmerich, Germany' },
  { pos: 20, name: 'V. Bottas', full: 'Valtteri Bottas', s: 'BOT', team: 'Cadillac', pts: 0, num: 77, nat: '🇫🇮', wins: 0, poles: 0, born: '1989', from: 'Nastola, Finland' },
  { pos: 21, name: 'S. Pérez', full: 'Sergio Pérez', s: 'PER', team: 'Cadillac', pts: 0, num: 11, nat: '🇲🇽', wins: 0, poles: 0, born: '1990', from: 'Guadalajara, Mexico' },
  { pos: 22, name: 'L. Stroll', full: 'Lance Stroll', s: 'STR', team: 'Aston Martin', pts: 0, num: 18, nat: '🇨🇦', wins: 0, poles: 0, born: '1998', from: 'Montreal, Canada' },
];

const CONS = [
  { pos: 1, name: 'Mercedes', pts: 244, c: '#00D2BE' },
  { pos: 2, name: 'Ferrari', pts: 165, c: '#DC143C' },
  { pos: 3, name: 'McLaren', pts: 118, c: '#FF8000' },
  { pos: 4, name: 'Red Bull', pts: 72, c: '#3671C6' },
  { pos: 5, name: 'Alpine', pts: 41, c: '#0090FF' },
  { pos: 6, name: 'Racing Bulls', pts: 39, c: '#6692FF' },
  { pos: 7, name: 'Haas', pts: 21, c: '#B6BABD' },
  { pos: 8, name: 'Williams', pts: 11, c: '#64C4FF' },
  { pos: 9, name: 'Audi', pts: 2, c: '#C8102E' },
  { pos: 10, name: 'Aston Martin', pts: 1, c: '#358C75' },
  { pos: 11, name: 'Cadillac', pts: 0, c: '#CCCCCC' },
];

const TEAM_COLORS = {
  'Mercedes': '#00D2BE', 'Ferrari': '#DC143C', 'McLaren': '#FF8000',
  'Red Bull': '#3671C6', 'Alpine': '#0090FF', 'Racing Bulls': '#6692FF',
  'Haas': '#B6BABD', 'Williams': '#64C4FF', 'Audi': '#C8102E',
  'Aston Martin': '#358C75', 'Cadillac': '#CCCCCC'
};

const CDN = 'https://media.formula1.com/image/upload/c_lfill,w_320/q_auto/d_common:f1:2026:fallback:driver:2026fallbackdriverright.webp/v1740000001/common/f1/2026';

const DRIVER_PHOTOS = {
  'ANT': `${CDN}/mercedes/andant01/2026mercedesandant01right.webp`,
  'HAM': `${CDN}/ferrari/lewham01/2026ferrarilewham01right.webp`,
  'RUS': `${CDN}/mercedes/georus01/2026mercedesgeorus01right.webp`,
  'LEC': `${CDN}/ferrari/chalec01/2026ferrarichalec01right.webp`,
  'PIA': `${CDN}/mclaren/oscpia01/2026mclarenoscpia01right.webp`,
  'NOR': `${CDN}/mclaren/lannor01/2026mclarenlannor01right.webp`,
  'VER': `${CDN}/redbullracing/maxver01/2026redbullracingmaxver01right.webp`,
  'HAD': `${CDN}/redbullracing/isahad01/2026redbullracingisahad01right.webp`,
  'LAW': `${CDN}/racingbulls/lialaw01/2026racingbullslialaw01right.webp`,
  'GAS': `${CDN}/alpine/piegas01/2026alpinepiegas01right.webp`,
  'BEA': `${CDN}/haasf1team/olibea01/2026haasf1teamolibea01right.webp`,
  'COL': `${CDN}/alpine/fracol01/2026alpinefracol01right.webp`,
  'LIN': `${CDN}/racingbulls/arvlin01/2026racingbullsarvlin01right.webp`,
  'SAI': `${CDN}/williams/carsai01/2026williamscarsai01right.webp`,
  'ALB': `${CDN}/williams/alealb01/2026williamsalealb01right.webp`,
  'OCO': `${CDN}/haasf1team/estoco01/2026haasf1teamestoco01right.webp`,
  'BOR': `${CDN}/audi/gabbor01/2026audigabbor01right.webp`,
  'ALO': `${CDN}/astonmartin/feralo01/2026astonmartinferalo01right.webp`,
  'HUL': `${CDN}/audi/nichul01/2026audinichul01right.webp`,
  'BOT': `${CDN}/cadillac/valbot01/2026cadillacvalbot01right.webp`,
  'PER': `${CDN}/cadillac/serper01/2026cadillacserper01right.webp`,
  'STR': `${CDN}/astonmartin/lanstr01/2026astonmartinlanstr01right.webp`,
};

const DRIVER_FALLBACK = {
  'ANT': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Andrea_Kimi_Antonelli_2024_Monza.jpg/200px-Andrea_Kimi_Antonelli_2024_Monza.jpg',
  'HAM': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg/200px-Lewis_Hamilton_2016_Malaysia_2.jpg',
  'RUS': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/George_Russell_%28driver%29.jpg/200px-George_Russell_%28driver%29.jpg',
  'LEC': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Charles_Leclerc_2019.jpg/200px-Charles_Leclerc_2019.jpg',
  'PIA': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Oscar_Piastri_2023_%28cropped%29.jpg/200px-Oscar_Piastri_2023_%28cropped%29.jpg',
  'NOR': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Lando_Norris_2023_Monza.jpg/200px-Lando_Norris_2023_Monza.jpg',
  'VER': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Max_Verstappen_2023_Mexico_podium_%28cropped%29.jpg/200px-Max_Verstappen_2023_Mexico_podium_%28cropped%29.jpg',
  'GAS': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Pierre_Gasly_2023_%28cropped%29.jpg/200px-Pierre_Gasly_2023_%28cropped%29.jpg',
  'ALO': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Fernando_Alonso_%282022_Bahrain_GP%29.jpg/200px-Fernando_Alonso_%282022_Bahrain_GP%29.jpg',
  'SAI': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Carlos_Sainz%2C_2023_Monaco_GP_%28cropped%29.jpg/200px-Carlos_Sainz%2C_2023_Monaco_GP_%28cropped%29.jpg',
  'ALB': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Alexander_Albon_2023_%28cropped%29.jpg/200px-Alexander_Albon_2023_%28cropped%29.jpg',
};

const CAL = [
  { rd: 1, flag: '🇦🇺', nm: 'Australian GP', circ: 'Albert Park, Melbourne', dates: 'Mar 6-8', st: 'done', sched: { fp1: 'Thu 01:30', fp2: 'Thu 05:00', fp3: 'Sat 01:30', q: 'Sat 05:00', r: 'Sun 04:00' } },
  { rd: 2, flag: '🇨🇳', nm: 'Chinese GP', circ: 'Shanghai Int. Circuit', dates: 'Mar 13-15', st: 'done', sprint: true, sched: { fp1: 'Thu 03:30', sq: 'Thu 07:00', sr: 'Fri 03:00', q: 'Fri 07:00', r: 'Sun 07:00' } },
  { rd: 3, flag: '🇯🇵', nm: 'Japanese GP', circ: 'Suzuka Circuit', dates: 'Mar 27-29', st: 'done', sched: { fp1: 'Thu 02:30', fp2: 'Thu 06:00', fp3: 'Sat 02:30', q: 'Sat 06:00', r: 'Sun 05:00' } },
  { rd: '✗', flag: '🇧🇭', nm: 'Bahrain GP', circ: 'Bahrain Int. Circuit', dates: 'Apr 10-12', st: 'cancelled' },
  { rd: '✗', flag: '🇸🇦', nm: 'Saudi Arabian GP', circ: 'Jeddah Corniche Circuit', dates: 'Apr 17-19', st: 'cancelled' },
  { rd: 4, flag: '🇺🇸', nm: 'Miami GP', circ: 'Miami International Autodrome', dates: 'May 1-3', st: 'done', sprint: true, sched: { fp1: 'Thu 17:30', sq: 'Thu 21:00', sr: 'Fri 17:00', q: 'Fri 21:00', r: 'Sun 20:00' } },
  { rd: 5, flag: '🇨🇦', nm: 'Canadian GP', circ: 'Circuit Gilles Villeneuve', dates: 'May 22-24', st: 'done', sprint: true, sched: { fp1: 'Thu 17:30', sq: 'Thu 21:00', sr: 'Fri 17:00', q: 'Fri 21:00', r: 'Sun 18:00' } },
  { rd: 6, flag: '🇲🇨', nm: 'Monaco GP', circ: 'Circuit de Monaco', dates: 'Jun 5-7', st: 'done', sched: { fp1: 'Thu 12:30', fp2: 'Thu 16:00', fp3: 'Sat 12:30', q: 'Sat 15:00', r: 'Sun 14:00' } },
  { rd: 7, flag: '🇪🇸', nm: 'Barcelona GP', circ: 'Circuit de Barcelona-Catalunya', dates: 'Jun 12-14', st: 'current', sched: { fp1: 'Thu 10:30', fp2: 'Thu 14:00', fp3: 'Sat 10:30', q: 'Sat 14:00', r: 'Sun 13:00' } },
  { rd: 8, flag: '🇦🇹', nm: 'Austrian GP', circ: 'Red Bull Ring, Spielberg', dates: 'Jun 26-28', st: 'upcoming', sched: { fp1: 'Thu 10:30', fp2: 'Thu 14:00', fp3: 'Sat 10:30', q: 'Sat 14:00', r: 'Sun 14:00' } },
  { rd: 9, flag: '🇬🇧', nm: 'British GP', circ: 'Silverstone Circuit', dates: 'Jul 3-5', st: 'upcoming', sprint: true },
  { rd: 10, flag: '🇧🇪', nm: 'Belgian GP', circ: 'Circuit de Spa-Francorchamps', dates: 'Jul 17-19', st: 'upcoming' },
  { rd: 11, flag: '🇭🇺', nm: 'Hungarian GP', circ: 'Hungaroring, Budapest', dates: 'Jul 24-26', st: 'upcoming' },
  { rd: 12, flag: '🇳🇱', nm: 'Dutch GP', circ: 'Circuit Zandvoort', dates: 'Aug 21-23', st: 'upcoming', sprint: true },
  { rd: 13, flag: '🇮🇹', nm: 'Italian GP', circ: 'Autodromo Nazionale Monza', dates: 'Sep 4-6', st: 'upcoming' },
  { rd: 14, flag: '🇪🇸', nm: 'Madrid GP', circ: 'Madring Street Circuit', dates: 'Sep 11-13', st: 'upcoming' },
  { rd: 15, flag: '🇦🇿', nm: 'Azerbaijan GP', circ: 'Baku City Circuit', dates: 'Sep 25-27', st: 'upcoming' },
  { rd: 16, flag: '🇸🇬', nm: 'Singapore GP', circ: 'Marina Bay Street Circuit', dates: 'Oct 9-11', st: 'upcoming', sprint: true },
  { rd: 17, flag: '🇺🇸', nm: 'US GP', circ: 'Circuit of the Americas, Austin', dates: 'Oct 23-25', st: 'upcoming' },
  { rd: 18, flag: '🇲🇽', nm: 'Mexico GP', circ: 'Autódromo Hermanos Rodríguez', dates: 'Oct 30-Nov 1', st: 'upcoming' },
  { rd: 19, flag: '🇧🇷', nm: 'São Paulo GP', circ: 'Autódromo José Carlos Pace', dates: 'Nov 6-8', st: 'upcoming' },
  { rd: 20, flag: '🇺🇸', nm: 'Las Vegas GP', circ: 'Las Vegas Street Circuit', dates: 'Nov 19-21', st: 'upcoming' },
  { rd: 21, flag: '🇶🇦', nm: 'Qatar GP', circ: 'Lusail International Circuit', dates: 'Nov 27-29', st: 'upcoming' },
  { rd: 22, flag: '🇦🇪', nm: 'Abu Dhabi GP', circ: 'Yas Marina Circuit', dates: 'Dec 4-6', st: 'upcoming' },
];

const TEAMS = [
  { name: 'Mercedes', c: '#00D2BE', pts: 244, d1: 'A. Antonelli', d1n: 12, d1p: 156, d2: 'G. Russell', d2n: 63, d2p: 88, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/mercedes-logo.png.transform/2col/image.png' },
  { name: 'Ferrari', c: '#DC143C', pts: 165, d1: 'L. Hamilton', d1n: 44, d1p: 90, d2: 'C. Leclerc', d2n: 16, d2p: 75, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/ferrari-logo.png.transform/2col/image.png' },
  { name: 'McLaren', c: '#FF8000', pts: 118, d1: 'O. Piastri', d1n: 81, d1p: 60, d2: 'L. Norris', d2n: 4, d2p: 58, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/mclaren-logo.png.transform/2col/image.png' },
  { name: 'Red Bull', c: '#3671C6', pts: 72, d1: 'M. Verstappen', d1n: 1, d1p: 43, d2: 'I. Hadjar', d2n: 6, d2p: 29, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/red-bull-racing-logo.png.transform/2col/image.png' },
  { name: 'Alpine', c: '#0090FF', pts: 41, d1: 'P. Gasly', d1n: 10, d1p: 26, d2: 'F. Colapinto', d2n: 43, d2p: 15, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/alpine-logo.png.transform/2col/image.png' },
  { name: 'Racing Bulls', c: '#6692FF', pts: 39, d1: 'L. Lawson', d1n: 30, d1p: 26, d2: 'A. Lindblad', d2n: 7, d2p: 13, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/rb-logo.png.transform/2col/image.png' },
  { name: 'Haas', c: '#B6BABD', pts: 21, d1: 'O. Bearman', d1n: 87, d1p: 18, d2: 'E. Ocon', d2n: 31, d2p: 3, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/haas-logo.png.transform/2col/image.png' },
  { name: 'Williams', c: '#64C4FF', pts: 11, d1: 'C. Sainz', d1n: 55, d1p: 6, d2: 'A. Albon', d2n: 23, d2p: 5, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/williams-logo.png.transform/2col/image.png' },
  { name: 'Audi', c: '#C8102E', pts: 2, d1: 'G. Bortoleto', d1n: 5, d1p: 2, d2: 'N. Hülkenberg', d2n: 27, d2p: 0, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/kick-sauber-logo.png.transform/2col/image.png' },
  { name: 'Aston Martin', c: '#358C75', pts: 1, d1: 'F. Alonso', d1n: 14, d1p: 1, d2: 'L. Stroll', d2n: 18, d2p: 0, logo: 'https://www.formula1.com/content/dam/fom-website/teams/2024/aston-martin-logo.png.transform/2col/image.png' },
  { name: 'Cadillac', c: '#CCCCCC', pts: 0, d1: 'V. Bottas', d1n: 77, d1p: 0, d2: 'S. Pérez', d2n: 11, d2p: 0, logo: '' },
];

const HIGHLIGHTS = [];

const TRACKS = [
  { name: 'Albert Park', country: '🇦🇺', city: 'Melbourne, Australia', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Australia_Circuit.png.transform/7col/image.png', laps: 58, len: '5.278 km', lap: '1:20.235', type: 'Street', turns: 16 },
  { name: 'Shanghai', country: '🇨🇳', city: 'Shanghai, China', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/China_Circuit.png.transform/7col/image.png', laps: 56, len: '5.451 km', lap: '1:32.238', type: 'Permanent', turns: 16 },
  { name: 'Suzuka', country: '🇯🇵', city: 'Suzuka, Japan', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Japan_Circuit.png.transform/7col/image.png', laps: 53, len: '5.807 km', lap: '1:30.983', type: 'Permanent', turns: 18 },
  { name: 'Miami International', country: '🇺🇸', city: 'Miami, Florida', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Miami_Circuit.png.transform/7col/image.png', laps: 57, len: '5.412 km', lap: '1:29.708', type: 'Street', turns: 19 },
  { name: 'Circuit Gilles Villeneuve', country: '🇨🇦', city: 'Montréal, Canada', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Canada_Circuit.png.transform/7col/image.png', laps: 70, len: '4.361 km', lap: '1:13.078', type: 'Street', turns: 14 },
  { name: 'Circuit de Monaco', country: '🇲🇨', city: 'Monte Carlo', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Monaco_Circuit.png.transform/7col/image.png', laps: 78, len: '3.337 km', lap: '1:12.909', type: 'Street', turns: 19 },
  { name: 'Barcelona-Catalunya', country: '🇪🇸', city: 'Barcelona, Spain', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit.png.transform/7col/image.png', laps: 66, len: '4.657 km', lap: '1:16.330', type: 'Permanent', turns: 14 },
  { name: 'Red Bull Ring', country: '🇦🇹', city: 'Spielberg, Austria', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Austria_Circuit.png.transform/7col/image.png', laps: 71, len: '4.318 km', lap: '1:05.619', type: 'Permanent', turns: 10 },
  { name: 'Silverstone', country: '🇬🇧', city: 'Northamptonshire, UK', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Great_Britain_Circuit.png.transform/7col/image.png', laps: 52, len: '5.891 km', lap: '1:27.097', type: 'Permanent', turns: 18 },
  { name: 'Spa-Francorchamps', country: '🇧🇪', city: 'Stavelot, Belgium', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Belgium_Circuit.png.transform/7col/image.png', laps: 44, len: '7.004 km', lap: '1:46.286', type: 'Permanent', turns: 19 },
  { name: 'Hungaroring', country: '🇭🇺', city: 'Budapest, Hungary', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit.png.transform/7col/image.png', laps: 70, len: '4.381 km', lap: '1:16.627', type: 'Permanent', turns: 14 },
  { name: 'Zandvoort', country: '🇳🇱', city: 'Zandvoort, Netherlands', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Netherlands_Circuit.png.transform/7col/image.png', laps: 72, len: '4.259 km', lap: '1:11.097', type: 'Permanent', turns: 14 },
  { name: 'Autodromo Nazionale Monza', country: '🇮🇹', city: 'Monza, Italy', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Italy_Circuit.png.transform/7col/image.png', laps: 53, len: '5.793 km', lap: '1:21.046', type: 'Permanent', turns: 11 },
  { name: 'Madring Street Circuit', country: '🇪🇸', city: 'Madrid, Spain', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Spain_Circuit.png.transform/7col/image.png', laps: 55, len: '5.476 km', lap: '1:17.500', type: 'Street', turns: 21 },
  { name: 'Baku City Circuit', country: '🇦🇿', city: 'Baku, Azerbaijan', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Baku_Circuit.png.transform/7col/image.png', laps: 51, len: '6.003 km', lap: '1:43.009', type: 'Street', turns: 20 },
  { name: 'Marina Bay', country: '🇸🇬', city: 'Singapore', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Singapore_Circuit.png.transform/7col/image.png', laps: 61, len: '4.940 km', lap: '1:35.867', type: 'Street', turns: 19 },
  { name: 'Circuit of the Americas', country: '🇺🇸', city: 'Austin, Texas', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/USA_Circuit.png.transform/7col/image.png', laps: 56, len: '5.513 km', lap: '1:36.169', type: 'Permanent', turns: 20 },
  { name: 'Autódromo Hermanos Rodríguez', country: '🇲🇽', city: 'Mexico City', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Mexico_Circuit.png.transform/7col/image.png', laps: 71, len: '4.304 km', lap: '1:17.774', type: 'Permanent', turns: 17 },
  { name: 'Autódromo José Carlos Pace', country: '🇧🇷', city: 'São Paulo, Brazil', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Brazil_Circuit.png.transform/7col/image.png', laps: 71, len: '4.309 km', lap: '1:10.540', type: 'Permanent', turns: 15 },
  { name: 'Las Vegas Strip Circuit', country: '🇺🇸', city: 'Las Vegas, Nevada', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Las_Vegas_Circuit.png.transform/7col/image.png', laps: 50, len: '6.201 km', lap: '1:35.490', type: 'Street', turns: 17 },
  { name: 'Lusail International', country: '🇶🇦', city: 'Lusail, Qatar', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Qatar_Circuit.png.transform/7col/image.png', laps: 57, len: '5.380 km', lap: '1:24.319', type: 'Permanent', turns: 16 },
  { name: 'Yas Marina', country: '🇦🇪', city: 'Abu Dhabi, UAE', img: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Abu_Dhabi_Circuit.png.transform/7col/image.png', laps: 58, len: '5.281 km', lap: '1:26.103', type: 'Permanent', turns: 16 },
];

const DRIVER_DETAILS = {
  'ANT': { bio: 'Andrea Kimi Antonelli is an Italian sensation who stepped directly from Formula 2 to Mercedes in 2026. A Mercedes junior since 2019, Antonelli has dominated junior categories and is hailed as one of the most exciting young talents in decades.', starts: 6, wins: 4, poles: 3, podiums: 5, championships: 0, races: [{ name: 'Australian GP', pos: 1 }, { name: 'Chinese GP', pos: 3 }, { name: 'Japanese GP', pos: 1 }, { name: 'Miami GP', pos: 1 }, { name: 'Canadian GP', pos: 2 }, { name: 'Monaco GP', pos: 1 }] },
  'HAM': { bio: 'Lewis Hamilton is a seven-time World Champion, statistically the most successful driver in Formula 1 history. For 2026, Hamilton made the historic switch to Ferrari, seeking a record-breaking eighth title in red.', starts: 350, wins: 104, poles: 106, podiums: 198, championships: 7, races: [{ name: 'Australian GP', pos: 2 }, { name: 'Chinese GP', pos: 2 }, { name: 'Japanese GP', pos: 5 }, { name: 'Miami GP', pos: 3 }, { name: 'Canadian GP', pos: 1 }, { name: 'Monaco GP', pos: 4 }] },
  'RUS': { bio: 'George Russell is a British Formula 1 race winner driving for Mercedes. Known for his stellar qualifying speed and analytical approach, Russell leads the Mercedes garage alongside rookie teammate Antonelli in 2026.', starts: 110, wins: 3, poles: 4, podiums: 12, championships: 0, races: [{ name: 'Australian GP', pos: 3 }, { name: 'Chinese GP', pos: 4 }, { name: 'Japanese GP', pos: 2 }, { name: 'Miami GP', pos: 2 }, { name: 'Canadian GP', pos: 5 }, { name: 'Monaco GP', pos: 3 }] },
  'LEC': { bio: 'Charles Leclerc is Ferrari\'s home-grown star. Extremely quick over a single lap, the Monegasque driver has captured numerous pole positions and race wins, and is now partnered with Lewis Hamilton at Maranello.', starts: 131, wins: 7, poles: 25, podiums: 32, championships: 0, races: [{ name: 'Australian GP', pos: 4 }, { name: 'Chinese GP', pos: 5 }, { name: 'Japanese GP', pos: 3 }, { name: 'Miami GP', pos: 4 }, { name: 'Canadian GP', pos: 3 }, { name: 'Monaco GP', pos: 2 }] },
  'PIA': { bio: 'Oscar Piastri is a highly-rated Australian driver racing for McLaren. After a sensational junior career where he won Formula 3 and Formula 2 back-to-back, Piastri has established himself as a future champion at McLaren.', starts: 48, wins: 2, poles: 2, podiums: 9, championships: 0, races: [{ name: 'Australian GP', pos: 5 }, { name: 'Chinese GP', pos: 6 }, { name: 'Japanese GP', pos: 4 }, { name: 'Miami GP', pos: 5 }, { name: 'Canadian GP', pos: 4 }, { name: 'Monaco GP', pos: 5 }] },
  'NOR': { bio: 'Lando Norris is a multiple Grand Prix winner and the talisman of McLaren. His speed, consistency, and popular personality have made him a leading figure in the sport\'s new generation.', starts: 110, wins: 2, poles: 2, podiums: 16, championships: 0, races: [{ name: 'Australian GP', pos: 6 }, { name: 'Chinese GP', pos: 1 }, { name: 'Japanese GP', pos: 6 }, { name: 'Miami GP', pos: 6 }, { name: 'Canadian GP', pos: 6 }, { name: 'Monaco GP', pos: 6 }] },
  'VER': { bio: 'Max Verstappen is a three-time World Champion who rewrote F1 record books with Red Bull Racing. Known for his ruthless race craft and raw speed, he continues to push the limits of his machinery.', starts: 191, wins: 62, poles: 40, podiums: 104, championships: 3, races: [{ name: 'Australian GP', pos: 10 }, { name: 'Chinese GP', pos: 11 }, { name: 'Japanese GP', pos: 7 }, { name: 'Miami GP', pos: 7 }, { name: 'Canadian GP', pos: 8 }, { name: 'Monaco GP', pos: 7 }] },
  'HAD': { bio: 'Isack Hadjar is Red Bull\'s latest junior prospect promoted to the senior team in 2026. Handpicked by Helmut Marko, the aggressive French-Algerian racer brings raw pace and high energy to the grid.', starts: 6, wins: 0, poles: 0, podiums: 1, championships: 0, races: [{ name: 'Australian GP', pos: 7 }, { name: 'Chinese GP', pos: 8 }, { name: 'Japanese GP', pos: 8 }, { name: 'Miami GP', pos: 10 }, { name: 'Canadian GP', pos: 7 }, { name: 'Monaco GP', pos: 9 }] },
  'LAW': { bio: 'Liam Lawson is a determined New Zealand racer who earned his full-time seat at Racing Bulls. Known for scoring points on debut, Lawson possesses a sharp racing brain and strong adaptability.', starts: 18, wins: 0, poles: 0, podiums: 0, championships: 0, races: [{ name: 'Australian GP', pos: 8 }, { name: 'Chinese GP', pos: 9 }, { name: 'Japanese GP', pos: 10 }, { name: 'Miami GP', pos: 8 }, { name: 'Canadian GP', pos: 9 }, { name: 'Monaco GP', pos: 8 }] },
  'GAS': { bio: 'Pierre Gasly is an experienced French Grand Prix winner driving for Alpine. Known for his emotional victory at Monza in 2020 and his resilience, Gasly leads the French squad\'s line-up.', starts: 146, wins: 1, poles: 0, podiums: 4, championships: 0, races: [{ name: 'Australian GP', pos: 9 }, { name: 'Chinese GP', pos: 7 }, { name: 'Japanese GP', pos: 9 }, { name: 'Miami GP', pos: 9 }, { name: 'Canadian GP', pos: 10 }, { name: 'Monaco GP', pos: 10 }] },
  'BEA': { bio: 'Oliver Bearman is a British prodigy driving for Haas. He made a spectacular F1 debut with Ferrari in Saudi Arabia in 2024, scoring points as a teenager, securing a full-time seat.', starts: 26, wins: 0, poles: 0, podiums: 0, championships: 0, races: [{ name: 'Australian GP', pos: 11 }, { name: 'Chinese GP', pos: 10 }, { name: 'Japanese GP', pos: 11 }, { name: 'Miami GP', pos: 11 }, { name: 'Canadian GP', pos: 11 }, { name: 'Monaco GP', pos: 11 }] },
  'COL': { bio: 'Franco Colapinto is an Argentine racer driving for Alpine. Having stepped up as a mid-season replacement in 2024, his impressive speed and huge South American fanbase earned him a long-term contract.', starts: 15, wins: 0, poles: 0, podiums: 0, championships: 0, races: [{ name: 'Australian GP', pos: 12 }, { name: 'Chinese GP', pos: 12 }, { name: 'Japanese GP', pos: 12 }, { name: 'Miami GP', pos: 12 }, { name: 'Canadian GP', pos: 12 }, { name: 'Monaco GP', pos: 12 }] },
  'LIN': { bio: 'Arvid Lindblad is a Red Bull junior racing for Racing Bulls in 2026. One of the youngest drivers on the grid, possessing rapid natural pace and a bright future.', starts: 6, wins: 0, poles: 0, podiums: 0, championships: 0, races: [{ name: 'Australian GP', pos: 13 }, { name: 'Chinese GP', pos: 13 }, { name: 'Japanese GP', pos: 13 }, { name: 'Miami GP', pos: 13 }, { name: 'Canadian GP', pos: 13 }, { name: 'Monaco GP', pos: 13 }] },
  'SAI': { bio: 'Carlos Sainz is a multi-time Grand Prix winner now driving for Williams. A highly technical driver with excellent tactical awareness, Sainz anchors Williams\' climb up the grid.', starts: 192, wins: 3, poles: 5, podiums: 21, championships: 0, races: [{ name: 'Australian GP', pos: 14 }, { name: 'Chinese GP', pos: 14 }, { name: 'Japanese GP', pos: 14 }, { name: 'Miami GP', pos: 14 }, { name: 'Canadian GP', pos: 14 }, { name: 'Monaco GP', pos: 14 }] },
  'ALB': { bio: 'Alexander Albon is a Thai-British driver who has revitalized Williams with his leadership and incredible point-scoring drives. Respected for his calm demeanor and overtaking prowess.', starts: 92, wins: 0, poles: 0, podiums: 2, championships: 0, races: [{ name: 'Australian GP', pos: 15 }, { name: 'Chinese GP', pos: 15 }, { name: 'Japanese GP', pos: 15 }, { name: 'Miami GP', pos: 15 }, { name: 'Canadian GP', pos: 15 }, { name: 'Monaco GP', pos: 15 }] },
  'OCO': { bio: 'Esteban Ocon is a French race winner driving for Haas in 2026. A highly defensive and gritty racer, Ocon\'s victory in Hungary 2021 proved his ability under extreme pressure.', starts: 140, wins: 1, poles: 0, podiums: 3, championships: 0, races: [{ name: 'Australian GP', pos: 16 }, { name: 'Chinese GP', pos: 16 }, { name: 'Japanese GP', pos: 16 }, { name: 'Miami GP', pos: 16 }, { name: 'Canadian GP', pos: 16 }, { name: 'Monaco GP', pos: 16 }] },
  'BOR': { bio: 'Gabriel Bortoleto is a Brazilian talent driving for Audi. After winning F3 and F2 championships in his rookie years, Bortoleto is highly regarded as Brazil\'s next F1 star.', starts: 6, wins: 0, poles: 0, podiums: 0, championships: 0, races: [{ name: 'Australian GP', pos: 17 }, { name: 'Chinese GP', pos: 17 }, { name: 'Japanese GP', pos: 17 }, { name: 'Miami GP', pos: 17 }, { name: 'Canadian GP', pos: 17 }, { name: 'Monaco GP', pos: 17 }] },
  'ALO': { bio: 'Fernando Alonso is a legendary two-time World Champion and one of the greatest drivers in F1 history. His longevity, racecraft, and relentless speed continue to amaze the paddock.', starts: 388, wins: 32, poles: 22, podiums: 106, championships: 2, races: [{ name: 'Australian GP', pos: 18 }, { name: 'Chinese GP', pos: 18 }, { name: 'Japanese GP', pos: 18 }, { name: 'Miami GP', pos: 18 }, { name: 'Canadian GP', pos: 18 }, { name: 'Monaco GP', pos: 18 }] },
  'HUL': { bio: 'Nico Hülkenberg is a highly experienced German driver racing for Audi. Renowned for his exceptional qualifying performances and reliability, he leads Audi\'s entry preparations in 2026.', starts: 210, wins: 0, poles: 1, podiums: 0, championships: 0, races: [{ name: 'Australian GP', pos: 19 }, { name: 'Chinese GP', pos: 19 }, { name: 'Japanese GP', pos: 19 }, { name: 'Miami GP', pos: 19 }, { name: 'Canadian GP', pos: 19 }, { name: 'Monaco GP', pos: 19 }] },
  'BOT': { bio: 'Valtteri Bottas is a 10-time Grand Prix winner racing for Cadillac. An ultra-consistent driver, Bottas brings vast experience to the new Cadillac project.', starts: 230, wins: 10, poles: 20, podiums: 67, championships: 0, races: [{ name: 'Australian GP', pos: 20 }, { name: 'Chinese GP', pos: 20 }, { name: 'Japanese GP', pos: 20 }, { name: 'Miami GP', pos: 20 }, { name: 'Canadian GP', pos: 20 }, { name: 'Monaco GP', pos: 20 }] },
  'PER': { bio: 'Sergio Pérez is a multiple Grand Prix winner from Mexico. Famously dubbed the "King of the Streets" for victories in Baku, Monaco, and Singapore, Perez drives for Cadillac in 2026.', starts: 260, wins: 6, poles: 3, podiums: 39, championships: 0, races: [{ name: 'Australian GP', pos: 21 }, { name: 'Chinese GP', pos: 21 }, { name: 'Japanese GP', pos: 21 }, { name: 'Miami GP', pos: 21 }, { name: 'Canadian GP', pos: 21 }, { name: 'Monaco GP', pos: 21 }] },
  'STR': { bio: 'Lance Stroll is a Canadian driver racing for Aston Martin. With multiple podium finishes and a pole position to his name, Stroll is a highly experienced and aggressive wet-weather driver.', starts: 150, wins: 0, poles: 1, podiums: 3, championships: 0, races: [{ name: 'Australian GP', pos: 22 }, { name: 'Chinese GP', pos: 22 }, { name: 'Japanese GP', pos: 22 }, { name: 'Miami GP', pos: 22 }, { name: 'Canadian GP', pos: 22 }, { name: 'Monaco GP', pos: 22 }] },
};

const TRACK_DETAILS = {
  'Albert Park': { history: 'First hosting a Formula 1 Grand Prix in 1996, Albert Park is a semi-permanent circuit built around Melbourne\'s scenic Albert Park Lake. It has historically served as the season-opening race and underwent major modifications in 2021 to increase speed and overtaking opportunities.', firstGP: '1996', capacity: '125,000', drsZones: '4 zones', recordHolder: 'Charles Leclerc (2022)' },
  'Shanghai': { history: 'Designed by Hermann Tilke, the Shanghai International Circuit opened in 2004. The track layout mimics the Chinese character "Shang" (上), meaning "to ascend." It features high-speed sweeps and a legendary 1.2km back straight.', firstGP: '2004', capacity: '200,000', drsZones: '2 zones', recordHolder: 'Michael Schumacher (2004)' },
  'Suzuka': { history: 'Suzuka Circuit is a legendary figure-eight track designed by John Hugenholtz in 1962 as a Honda test facility. Features iconic corners like the high-speed 130R and the flowing Esses.', firstGP: '1987', capacity: '155,000', drsZones: '1 zone', recordHolder: 'Lewis Hamilton (2019)' },
  'Circuit de Monaco': { history: 'Monaco is the jewel in the Formula 1 crown. This narrow, twisting street circuit winding through Monte Carlo is the ultimate test of precision and bravery, where qualifying is almost everything.', firstGP: '1950', capacity: '37,000', drsZones: '1 zone', recordHolder: 'Lewis Hamilton (2021)' },
  'Barcelona-Catalunya': { history: 'The Circuit de Barcelona-Catalunya has hosted the Spanish GP since 1991. Its layout offers a perfect blend of high, medium, and low-speed corners, making it the ultimate benchmark for aerodynamic performance.', firstGP: '1991', capacity: '140,000', drsZones: '2 zones', recordHolder: 'Max Verstappen (2021)' },
  'Silverstone': { history: 'Silverstone is the birthplace of the F1 World Championship, hosting the first-ever race in 1950. Built on a former WWII airfield, this ultra-fast, flowing track features legendary sequences like Copse, Becketts, and Chapel.', firstGP: '1950', capacity: '150,000', drsZones: '2 zones', recordHolder: 'Max Verstappen (2020)' },
  'Spa-Francorchamps': { history: 'Spa-Francorchamps is a legendary circuit in the Ardennes forest of Belgium. Spanning over 7km, it is the longest track on the calendar, hosting epic corners like Eau Rouge, Raidillon, and Pouhon.', firstGP: '1950', capacity: '100,000', drsZones: '2 zones', recordHolder: 'Valtteri Bottas (2018)' },
  'Autodromo Nazionale Monza': { history: 'Monza is F1\'s historic "Temple of Speed." Hosting the Italian GP almost every year since 1950, it features long straights and fast chicanes where cars reach top speeds of over 350 km/h.', firstGP: '1950', capacity: '115,000', drsZones: '2 zones', recordHolder: 'Rubens Barrichello (2004)' },
  'Circuit Gilles Villeneuve': { history: 'Located on Notre Dame Island in Montreal, this fast, low-downforce street circuit has hosted the Canadian GP since 1978. Famous for the "Wall of Champions" at the final chicane.', firstGP: '1978', capacity: '100,000', drsZones: '3 zones', recordHolder: 'Valtteri Bottas (2019)' },
  'Red Bull Ring': { history: 'Located in the Styrian mountains, the Red Bull Ring has just 10 corners but features significant elevation changes and high-speed straights.', firstGP: '1970', capacity: '105,000', drsZones: '3 zones', recordHolder: 'Carlos Sainz (2020)' },
  'Circuit of the Americas': { history: 'Located in Austin, Texas, COTA was the first purpose-built F1 facility in the US. Features an iconic climb to Turn 1 and borrows inspiration from famous tracks worldwide.', firstGP: '2012', capacity: '120,000', drsZones: '2 zones', recordHolder: 'Charles Leclerc (2019)' },
  'Yas Marina': { history: 'Yas Marina is F1\'s spectacular day-night season finale. Features a unique pit lane exit tunnel, a run underneath a hotel, and underwent layout changes in 2021 to make races more exciting.', firstGP: '2009', capacity: '60,000', drsZones: '2 zones', recordHolder: 'Max Verstappen (2021)' },
};
